### ISSUE TITLE
Atomic nodes are too small

### ISSUE THREAD

**Issue by leMaik** [BuggyOrg/graphify#4]
![image](https://cloud.githubusercontent.com/assets/5544859/15802599/ac069ea8-2ab7-11e6-83bc-87481d71623a.png)
Looks like they are not wide enough (i.e. left padding not being added to the width).

**Comment by LittleHelicase** [comment]
We measured the wrong font. Solved via 8f6f5d884c39199d6044fc91b147cb0be85744f6
